# Base configs
baseurl: "https://photography.coastalpeaks.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Ram Patra"
subtitle: "See the world through my eyes!"
author: "Ram Patra"
header:
 title: "Photography"
 subtitle: "by jmssrfs"
footer:
 name: 
 bio:
 github: 
web_design: "AJ"
social_urls:
  facebook:
  twitter: 
  instagram: 
  dribbble:
  linkedin: 
  github: 
